import type { Location, Category, Event, Destination, HypeArticle, QuickPrompt, ChatMessage } from './types';

export const locations: Record<string, Location> = {
  beograd: {
    id: 'beograd',
    name: 'Beograd',
    country: 'Srbija',
    lat: 44.8176,
    lng: 20.4554,
  },
  novi_sad: {
    id: 'novi_sad',
    name: 'Novi Sad',
    country: 'Srbija',
    lat: 45.2671,
    lng: 19.8335,
  },
  nis: {
    id: 'nis',
    name: 'Niš',
    country: 'Srbija',
    lat: 43.3209,
    lng: 21.8956,
  },
  zagreb: {
    id: 'zagreb',
    name: 'Zagreb',
    country: 'Hrvatska',
    lat: 45.815,
    lng: 15.9819,
  },
  sarajevo: {
    id: 'sarajevo',
    name: 'Sarajevo',
    country: 'Bosna i Hercegovina',
    lat: 43.9159,
    lng: 18.4131,
  },
};

export const categories: Record<string, Category> = {
  events: {
    id: 'events',
    name: 'Događaji',
    icon: 'Calendar',
    color: '#ec4899',
  },
  travel: {
    id: 'travel',
    name: 'Putovanja',
    icon: 'MapPin',
    color: '#3b82f6',
  },
  music: {
    id: 'music',
    name: 'Muzika',
    icon: 'Music',
    color: '#f59e0b',
  },
  restaurants: {
    id: 'restaurants',
    name: 'Restorani',
    icon: 'Utensils',
    color: '#f97316',
  },
  nightlife: {
    id: 'nightlife',
    name: 'Noćni život',
    icon: 'Sparkles',
    color: '#8b5cf6',
  },
  celebrities: {
    id: 'celebrities',
    name: 'Poznati',
    icon: 'Star',
    color: '#06b6d4',
  },
};

export const quickPrompts: QuickPrompt[] = [
  {
    id: '1',
    text: 'Gde izaći večeras?',
    icon: 'Music',
  },
  {
    id: '2',
    text: 'Planiraj putovanje',
    icon: 'Map',
  },
  {
    id: '3',
    text: 'Šta je ovog vikenda?',
    icon: 'Calendar',
  },
  {
    id: '4',
    text: 'Šta je popularno?',
    icon: 'TrendingUp',
  },
];

export const events: Event[] = [
  {
    id: 'event1',
    title: 'EXIT Festival',
    description: 'Najveći muzički festival u Jugoistočnoj Evropi',
    date: '2024-08-09',
    location: locations.novi_sad,
    imageUrl: '/mock-images/exit.svg',
    category: categories.music,
    price: 69,
    duration: '4 dana',
  },
  {
    id: 'event2',
    title: 'Belef Festival',
    description: 'Međunarodni festival savremene umetnosti',
    date: '2024-08-02',
    location: locations.nis,
    imageUrl: '/mock-images/belef.svg',
    category: categories.events,
    price: 45,
    duration: '7 dana',
  },
  {
    id: 'event3',
    title: 'Dragslaff Craft Beer Festival',
    description: 'Predstavljanje najboljih srpskih i regionalnih kraft pivara',
    date: '2024-08-17',
    location: locations.beograd,
    imageUrl: '/mock-images/craft-beer.svg',
    category: categories.restaurants,
    price: 15,
    duration: '1 dan',
  },
  {
    id: 'event4',
    title: 'Lake Bled Festival',
    description: 'Letnji kulturni festival pored jezera',
    date: '2024-08-16',
    location: {
      id: 'bled',
      name: 'Bled',
      country: 'Slovenija',
      lat: 46.3643,
      lng: 14.1128,
    },
    imageUrl: '/mock-images/bled.svg',
    category: categories.travel,
    price: 35,
    duration: '5 dana',
  },
];

export const destinations: Destination[] = [
  {
    id: 'dest1',
    name: 'Kalemegdan',
    description: 'Istorijska tvrđava iznad ušća Save u Dunav',
    imageUrl: '/mock-images/kalemegdan.svg',
    location: locations.beograd,
    rating: 4.8,
    category: categories.travel,
    bestTime: 'april - oktobar',
    duration: '2-3 sata',
  },
  {
    id: 'dest2',
    name: 'Dunav',  
    description: 'Panoramsko krstarenje i šetnja uz reku',
    imageUrl: '/mock-images/dunav.svg',
    location: locations.beograd,
    rating: 4.6,
    category: categories.travel,
    bestTime: 'maj - septembar',
    duration: '1-4 sata',
  },
  {
    id: 'dest3',
    name: 'Zemun',
    description: 'Šarmantna četvrt sa austrougarskom arhitekturom i šetalištem uz Dunav',
    imageUrl: '/mock-images/zemun.svg',
    location: locations.beograd,
    rating: 4.7,
    category: categories.travel,
    bestTime: 'april - oktobar',
    duration: '2-4 sata',
  },
  {
    id: 'dest4',
    name: 'Tvrđava Ras',
    description: 'Srednjovekovna tvrđava i značajan istorijski lokalitet',
    imageUrl: '/mock-images/ras.svg',
    location: locations.nis,
    rating: 4.5,
    category: categories.travel,
    bestTime: 'april - oktobar',
    duration: '2-3 sata',
  },
  {
    id: 'dest5',
    name: 'Plitvice Lakes',
    description: 'UNESCO lokalitet sa jezerima i raskošnim slapovima',
    imageUrl: '/mock-images/plitvice.svg',
    location: {
      id: 'plitvice',
      name: 'Plitvice',
      country: 'Hrvatska',
      lat: 44.8654,
      lng: 15.5821,
    },
    rating: 4.9,
    category: categories.travel,
    bestTime: 'april - oktobar',
    duration: '4-8 sati',
  },
  {
    id: 'dest6',
    name: 'Dunav River Gorge',
    description: 'Spektakularna klisura i vidikovci duž Dunava',
    imageUrl: '/mock-images/djerdap.svg',
    location: {
      id: 'golubac',
      name: 'Golubac',
      country: 'Srbija',
      lat: 44.5545,
      lng: 21.8194,
    },
    rating: 4.7,
    category: categories.travel,
    bestTime: 'maj - septembar',
    duration: '3-4 sata',
  },
];

export const hypeArticles: HypeArticle[] = [
  {
    id: 'article1',
    title: 'Top 5 skrivenih kraft pivnica u Beogradu',
    excerpt: 'Otkrij najbolju kraft scenu van poznatih lokala',
    content: 'Detaljan vodič kroz kraft pivnice u Beogradu...',
    imageUrl: '/mock-images/craft-beer.svg',
    author: 'Marko Marković',
    publishedAt: '2024-07-20',
    category: categories.restaurants,
    readTime: 5,
  },
  {
    id: 'article2',
    title: 'Leto na Balkanu: kompletan vodič',
    excerpt: 'Sve što treba da znaš za letnje doživljaje u Jugoistočnoj Evropi',
    content: 'Sveobuhvatan vodič kroz letnje aktivnosti na Balkanu...',
    imageUrl: '/mock-images/summer-balkans.svg',
    author: 'Jelena Jovanović',
    publishedAt: '2024-07-18',
    category: categories.travel,
    readTime: 8,
  },
  {
    id: 'article3',
    title: 'Street art scena: od Beograda do Zagreba',
    excerpt: 'Istraži živu kulturu ulične umetnosti širom Balkana',
    content: 'Vodič kroz najzanimljivije street art lokacije...',
    imageUrl: '/mock-images/street-art.svg',
    author: 'Ana Nikolić',
    publishedAt: '2024-07-15',
    category: categories.travel,
    readTime: 6,
  },
  {
    id: 'article4',
    title: 'Veganska i vegetarijanska scena na Balkanu',
    excerpt: 'Otkrij odlične restorane sa biljnom kuhinjom',
    content: 'Priča o najboljim veganskim i vegetarijanskim restoranima...',
    imageUrl: '/mock-images/vegan.svg',
    author: 'Lena Pavljenović',
    publishedAt: '2024-07-12',
    category: categories.restaurants,
    readTime: 7,
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    role: 'user',
    content: 'Šta ima zanimljivo u Beogradu za festival ljubitelje?',
    timestamp: '2024-07-25T18:30:00Z',
    context: {
      location: locations.beograd,
      language: 'sr',
      interests: ['music', 'culture'],
    },
  },
  {
    id: '2',
    role: 'assistant',
    content: 'Preporučujem ti da posjetiš nekoliko odličnih festivala ovog leta. Na osnovu tvojih interesa, siguran sam da će ti se svide.',
    timestamp: '2024-07-25T18:31:00Z',
  },
];

export const defaultUserPreferences = {
  city: 'Beograd',
  country: 'Srbija',
  language: 'sr',
  currency: 'RSD',
  interests: ['music', 'food', 'culture'],
  recommendationStyle: 'balanced' as const,
  savedItems: [],
};
